site:
  title: Roman Podoliaka's Blog
  author: Roman Podoliaka
  url: http://podoliaka.org/

theme:
  navigation: !!pairs
    - about: /about
    - talks: /talks
    - CV: https://www.dropbox.com/s/j8n1yd86dn00a41/cv.pdf?dl=1
    - feed: /feed.xml

  counters:
    google_analytics: UA-37812430-1

  copyright: >
    &copy; 2018 Roman Podoliaka

ext:
  enabled:
    - markdown
    - restructuredtext
    - index
    - feed
    - sitemap
    - tags
    - user-theme
