name: Build and Deploy

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install holocron

      - name: Build artifacts
        run: |
          holocron build

      - name: Deploy artifacts
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build
